apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-receiver
  namespace: staging-mn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-receiver
        namespace: staging-mn
    spec:
      containers:
      - name: order-receiver
        image: cubeiocorp/sample-order-receiver:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
          - name: cube_record_service
            value: "http://demo.dev.cupecorp.io/"
          - name:  cube_mock_service
            value: "http://demo.dev.cupecorp.io/"
          - name: io.md.customer
            value: "OrderCN"
          - name: io.md.app
            value: "OrderApp"
          - name: io.md.instance
            value: "test-order"
          - name: io.md.service
            value: "OrderReceiver"
          - name: read_timeout
            value: "100000"
          - name: connect_timeout
            value: "100000"
          - name: retries
            value: "3"
          - name: io.md.intent
            value: "record"
