##################################################################################################
# Order Receiver service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: order-receiver
  namespace: staging-mn
  labels:
    app: order-receiver
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: order-receiver
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-receiver
  namespace: staging-mn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-receiver
        namespace: staging-mn
    spec:
      containers:
      - name: order-receiver
        image: cubeiocorp/sample-order-receiver:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
          - name: cube_record_service
            value: "http://demo.dev.cupecorp.io/"
          - name:  cube_mock_service
            value: "http://demo.dev.cupecorp.io/"
          - name: customer_dogfood
            value: "cube"
          - name: app_dogfood
            value: "ordermanagement"
          - name: instance_dogfood
            value: "prod"
          - name: service_dogfood
            value: "wrapper"
          - name: read_timeout
            value: "100000"
          - name: connect_timeout
            value: "100000"
          - name: retries
            value: "3"
          - name: intent
            value: "record"
---
##################################################################################################
# Order Processor service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: order-processor
  namespace: staging-mn
  labels:
    app: order-processor
spec:
  ports:
  - port: 9080
    name: http
    targetPort: 8082
  selector:
    app: order-processor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-processor
  namespace: staging-mn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-processor
        namespace: staging-mn
    spec:
      containers:
      - name: order-processor
        image: cubeiocorp/sample-order-processor:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - containerPort: 8082
        env:
          - name: cube_record_service
            value: "http://demo.dev.cupecorp.io/"
          - name:  cube_mock_service
            value: "http://demo.dev.cupecorp.io/"
          - name: customer_dogfood
            value: "cube"
          - name: app_dogfood
            value: "app"
          - name: instance_dogfood
            value: "prod"
          - name: service_dogfood
            value: "wrapper"
          - name: read_timeout
            value: "100000"
          - name: connect_timeout
            value: "100000"
          - name: retries
            value: "3"
          - name: intent
            value: "record"
---
##################################################################################################
# Order Transformer service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: order-transformer
  namespace: staging-mn
  labels:
    app: order-transformer
spec:
  ports:
  - port: 9080
    name: http
    targetPort: 8081
  selector:
    app: order-transformer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-transformer
  namespace: staging-mn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-transformer
        namespace: staging-mn
    spec:
      containers:
      - name: order-transformer
        image: cubeiocorp/sample-order-transformer:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "130Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 8081
